README.md
[Featured actions from the GitHub Actions Hackathon - The GitHub Blog](https://github.blog/2020-04-09-featured-actions-from-the-github-actions-hackathon/)
Thank you all.
=> docs: Add link to GitHub blog

.github/label-commenter-config.yml, .prettierrc.json, __tests__/get-inputs.test.ts, package-lock.json, package.json, src/main.ts
- https://github.com/janl/mustache.js
cf. #152
=> feat: Add placeholder feature

src/main.ts
=> feat: Add user.login

.github/label-commenter-config.yml, .github/workflows/label-commenter.yml, src/main.ts
=> feat: Add issue.user.login

.github/workflows/label-commenter.yml, src/main.ts
=> feat: Add pull_request.user.login

package-lock.json, package.json, src/main.ts
- https://github.com/octokit/webhooks.js/blob/master/src/generated/event-payloads.ts
=> feat: use octokit/webhooks

.github/labeler.yml, .github/workflows/labeler.yml
related to #326
[actions/labeler: An action for automatically labelling pull requests](https://github.com/actions/labeler)
=> ci: Add actions/labeler

README.md
=> docs: Add example of actions/labeler

README.md
=> docs: add Work with Issue Template

tsconfig.json
[Announcing TypeScript 4.1 | TypeScript](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#checked-indexed-accesses-nouncheckedindexedaccess)
=> refactor: enable noUncheckedIndexedAccess

.husky/post-merge, .husky/pre-commit, package-lock.json, package.json
- deps: update devDependencies
- ci: Migrate husky from v4 to v5
=> deps: update devDependencies

.github/workflows/label-commenter.yml
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions
=> ci: Add permissions

README.md
=> docs: Add permissions

.github/workflows/codeql-analysis.yml, .github/workflows/dev-image.yml, .github/workflows/label-commenter.yml, .github/workflows/labeler.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/update-major-tag.yml
- ci: Add permissions
- ci: Add timeout-minutes
- ci: Add COMPOSE_DOCKER_CLI_BUILD and DOCKER_BUILDKIT
=> ci: Improve workflows

package-lock.json, package.json, src/main.ts
See https://github.com/octokit/webhooks/issues/447
=> deps: Use octokit/webhooks-types

.eslintrc.json, __tests__/get-inputs.test.ts, package-lock.json, package.json, src/get-inputs.ts, src/index.ts, src/issues-helper.ts, src/main.ts
- [benmosher/eslint-plugin-import: ESLint plugin with rules that help validate proper imports.](https://github.com/benmosher/eslint-plugin-import)
- [alexgorbatchev/eslint-import-resolver-typescript: This plugin adds TypeScript support to `eslint-plugin-import`.](https://github.com/alexgorbatchev/eslint-import-resolver-typescript)
=> style: Install eslint-plugin-import

.github/workflows/licensed.yml, .licensed.yml
https://github.com/github/licensed 3.7.3
cf. https://github.com/actions/setup-go/blob/268d8c0ca0432bb2cf416faae41297df9d262d7f/.licensed.yml
=> ci: add Licensed workflow

.husky/post-merge, __tests__/classes/inputs.test.ts, src/classes/action-processor.ts, src/classes/config.ts, src/classes/context-loader.ts, src/classes/issue.ts, src/main.ts
- refactor: check error type
- chore: replace npm ci with install
- test: replace toThrowError with toThrow
=> test: replace toThrowError with toThrow

.github/workflows/label-commenter.yml
Reverts peaceiris/actions-label-commenter#667
=> Revert "chore(deps): update peaceiris/actions-label-commenter digest to aa6d855"

package-lock.json
Reverts peaceiris/actions-label-commenter#838
=> Revert "chore(deps): update dependency nock to v13.3.8"
